baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'SQL Book'

theme = "hugo-theme-relearn"

canonifyURLs = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

  [params]
  alwaysopen = true
  disableBreadcrumb = false
  disableNextPrev = false
  ordersectionsby = "weight"
  collapsibleMenu = true
